name: Erlang CI

on:
  push:
    branches: [ master ]
    tags: ['v*']
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.3, 23.3, 24.1]

    container:
      image: erlang:${{ matrix.node-version }}

    steps:
      - uses: actions/checkout@v2

      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - name: Compile with OTP ${{ matrix.node-version }}
        run: rebar3 compile
