name: Node.js CI

on:
  push:
    branches: [master]
    tags: ['v*']
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Use Node.js 13
        uses: actions/setup-node@v4
        with:
          node-version: 13
          cache: 'npm'
      - run: yarn install
      - run: yarn build
      - run: yarn test
